### ISSUE TITLE
v0.17.0 release checklist

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1331]
We should probably make a v0.17.0 release soon, there have been lots of major changes since v0.16.

Please don't hesitate to update the https://github.com/iodide-project/pyodide/milestone/4 tag.

In technical blockers I see,
 - [x] to get a consistent version for type conversions and update the documentation https://github.com/iodide-project/pyodide/pull/1233 What it's left there in your opinion @hoodmane ?
 - [x] make the migration to a separate org https://github.com/iodide-project/pyodide/issues/1217
 - [x] make sure PyProxy and JsProxy methods are documented.

It would have also been nice to move forward on numpy (https://github.com/iodide-project/pyodide/pull/887) / scipy (https://github.com/iodide-project/pyodide/pull/1293) version updates but it is time consuming and I'm not sure it would be done.

**Comment by hoodmane** [comment]
The type conversions stuff is in good shape, when the buffers stuff gets merged I think there's mostly only polish and documentation left to do. I think the polish can be left to future releases. The docs on #1233 are accurate aside from the buffers. One question is what to do with the current `toJs` code for buffers. I would sort of like to get rid of it in favor of the `getRawBuffer` API which is faster and safer, but the `getRawBuffer` API is less user friendly. `getRawBuffer` is really intended to be used with some sort of `ndarray` library (I have confirmation from @daoxian that it works well for this).

I'd like to merge most of my open (non draft) PRs. Other than that, more work needs to be done on docs and it could be nice to hunt down some more memory leaks.

**Comment by hoodmane** [comment]
Oh another concern: Method resolution order for proxies.
Currently Python attributes override PyProxy method overloads always. We haven't explained this in the docs. Also if I make a Python class with a "destroy" field / method, the `PyProxy` destroy method becomes inaccessible, which might not be the greatest thing.

On the other hand, `JsProxy` methods override fields of the same name on the javascript object. It'd probably be good to change this to match the behavior of `PyProxy`?

**Comment by rth** [comment]
Please tag issues/PRs you would like to include in the release so we have an overall view.

> Oh another concern: Method resolution order for proxies.

Yeah, I guess documentation on that would be a start.

**Comment by hoodmane** [comment]
The current master branch is our release candidate for version 0.17.0, scheduled for release this upcoming Thursday. If any of you could try it out before then and give us feedback, it'd be much appreciated!

@dmondev @jmsmdy @johnwason @josephrocca @casatir @joemarshall @oeway @daoxian @albertas @jps1 @ChristopherHButler

**Comment by casatir** [comment]
Great!  I'll deploy it on Basthon's devel branch and launch the test suite. I'll let you know. Thanks!

**Comment by dmondev** [comment]
Awesome !! Will test for sure !!

**Comment by oeway** [comment]
Thanks for the great work! I will test it!

**Comment by dmondev** [comment]
@rth, 

Is this branch published as  "https://cdn.jsdelivr.net/pyodide/dev/full" ?
If this is the case, I'm still facing "memory access out of bounds"
I updated the MRE/codepen: https://codepen.io/dmondev/pen/eYgdBmm (Everything is in the HTML tab).

**Comment by rth** [comment]
Thanks for the report @dmondev !

I can reproduce with `pd.DataFrame(data=np.arange(3), columns=["values"]).to_json()` in the console, but for me the dev REPL currently shows,
```
Python 3.8.2 (default, Apr 17 2021 17:27:30) on WebAssembly VM
```
we had an issue with the deployment of the dev version the last few days, so it's likely it's still the version before the https://github.com/pyodide/pyodide/pull/1474. The latest version `main` was deployed to the dev CDN 20 min ago, but there is a 1 hours cache duration so we might need to wait a bit for JsDelivr to serve it. (Or rebuild main locally).

**Comment by hoodmane** [comment]
Thanks for the bug report!
Chrome 89 with 0.17.0 is going to have issues like this =(. Maybe we can add more patches and publish fixes as 0.17.x.

**Comment by dmondev** [comment]
Sorry, missed mentioning chrome version:

Chrome: Version 90.0.4430.72 (Official Build) (64-bit)

I'm getting the following now, with or without chrome dev tools:

I don't want to pollute this thread, but not sure the best way to keep reporting these (as new issues ? as part of this thread ?)

I have another pen, this time for using fetch: https://codepen.io/dmondev/pen/WNRgqqa?editors=1000

```
pyodide.asm.js:9 Assertion failed: undefined
abort @ pyodide.asm.js:9
pyodide.asm.js:9 RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
abort @ pyodide.asm.js:9
pyodide.asm.js:9 exception thrown: RuntimeError: abort(RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.,RuntimeError: abort(RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at abort (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9:140426)
    at _fd_read (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9:475814)
    at read (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[9946]:0x7247d3)
    at _Py_read (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[3620]:0x3043d8)
    at https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[6325]:0x428649
    at __static_3145 (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[6326]:0x428707)
    at byn$fpcast-emu$__static_3145 (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[24587]:0x7c679b)
    at __static_679 (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[1622]:0x2123b1)
    at byn$fpcast-emu$__static_679 (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[22121]:0x7bdcf0)
    at __static_3207 (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[6404]:0x42cd9c)
```

**Comment by rth** [comment]
As new issues would be best.

**Comment by hoodmane** [comment]
@dmondev Thanks so much for these reports!!

**Comment by ondrej-stanek-ozobot** [comment]
Thanks for the 0.17.0 preview!

We observe that the stack frame is approx 18% larger in pyodide version 0.17.0 (as of rev. c32740582e00a20f7f0c02cc6f2b4d1c4c65678a), compared to pyodide versions 0.14.1 and 0.15.0. 
However, we see an improvement in this aspect when comparing version 0.17.0 to version 0.16.1.

We are concerned about the stack frame size as some modules (jedi, in our case) tend to cause JavaScript stack overflow. Our solution to the issue was to compile python with `-Os` optimization flag instead of `-O2`.

Is the size of a stack frame and the stack use in general something that the pyodide team is concerned about? If so, I can create a ticket and elaborate more on the methods we use to estimate stack frame size.

**Comment by hoodmane** [comment]
> I can create a ticket and elaborate more on the methods we use to estimate stack frame size.

Yes! That would be great! I am very interested. It would be great to get `jedi` to work better in particular.

**Comment by hoodmane** [comment]
@ondrej-stanek-ozobot If you have a tool to estimate stack size, we should add it to the CI so it will be easier to hunt down regressions.

**Comment by jps1** [comment]
I've been using https://cdn.jsdelivr.net/pyodide/dev/full today, and have several times run into things like this:
![image](https://user-images.githubusercontent.com/8582709/115480151-c7283c00-a1fe-11eb-8176-9abeb8d09256.png)
I've seen out-of-memory issues occasionally before, but usually I'd close the tab, reopen, and it would be better.  These seem a bit more persistent.  Also, my understanding is that there were fixes in v0.17 that were intended to address this, so... I guess it's not working for me (and may have made things worse)?  I don't really have a consistent repro case, but if there's any info I can provide to help you debug, let me know.

I'm on Firefox 87.0.

**Comment by hoodmane** [comment]
@rth We have an existing issue about the errors @jps1 mentioned don't we?

> there were fixes in v0.17 that were intended to address this

That isn't true, I have seen that error on occasion but do not understand the trigger conditions and have not made any serious effort to fix it. The fixes I made were due to fatal memory access errors specifically in numpy in chrome 89.

> any info I can provide to help you debug, let me know.

Things I would suggest if you want to help fix this:
1. see if there is anything about it in other wasm projects' issues or the firefox issue tracker
2. consistent reproduction -- this might be hard though =(
3. compile with `EXTRA_LDFLAGS="-s ASSERTIONS=1"` or perhaps better `EXTRA_LDFLAGS="-s ASSERTIONS=2` and try to trigger it, see if it actually has any useful info there.

**Comment by hoodmane** [comment]
@jps1 Also when you see the errors consistently, does it make them go away if you close and restart firefox? What if you restart the computer?

**Comment by jps1** [comment]
> > there were fixes in v0.17 that were intended to address this
> 
> That isn't true, I have seen that error on occasion but do not understand the trigger conditions and have not made any serious effort to fix it. The fixes I made were due to fatal memory access errors specifically in numpy in chrome 89.

Ah, my bad... I just saw the bugs in passing and didn't pay too much attention.  I should have checked before stating that.

> 
> @jps1 Also when you see the errors consistently, does it make them go away if you close and restart firefox? What if you restart the computer?

Yes, closing and restarting firefox does appear to fix it.  I also poked around in "about:memory" to see if there was anything useful.  Perhaps this is notable:

![image](https://user-images.githubusercontent.com/8582709/115481990-83cfcc80-a202-11eb-8e6d-534bc03deb34.png)

Anytime I see things going wrong near 4GB, I start to get suspicious there's some 32-bit limit rearing its head...

**Comment by hoodmane** [comment]
Probably the top priority is making sure there's something about this in the firefox issue tracker.

**Comment by rth** [comment]
> Anytime I see things going wrong near 4GB, I start to get suspicious there's some 32-bit limit rearing its head...

yes, opened an issue and answered in https://github.com/pyodide/pyodide/issues/1513

**Comment by casatir** [comment]
Hi!

Just to let you know that my first tests on future 0.17.0 in Basthon looks good! Congratulation to all contributors!

Until now, I have only few and minor issues that should not prevent the release. I'll submit issues/PR to help fixing this.

Regards.

**Comment by rth** [comment]
Thanks for checking @casatir !

I think we are all set for the release https://github.com/pyodide/pyodide/pull/1515.
In more minor points, maybe we could try to fix https://github.com/pyodide/pyodide/issues/1516 if we make it it time.
