### ISSUE TITLE
Release 0.22

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3340]
Last week, Roman and I talked about releasing Pyodide 0.22 soon (maybe before the new year, but can be delayed as most of us might go winter vacation).

This issue is to summarize what needs to be done before releasing 0.22. I listed things that I can remember. Please add more if you think something is need to be done before 0.22.

__What needs to be done before 0.22__

- [x] Finish Hood's work on JsProxy/PyProxy iterator / generator
  - #3346
  - #3317
- [x] #3268
- [x] Release micropip 0.2.0 and use it in Pyodide  https://github.com/pyodide/pyodide/pull/3347
  - Pyodide docs should have a link to micropip docs.
  - Link external references using [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) plugin.
- [x] #3263
- [x] #3308
- [x] ~~#3092 (probably we need to rename the key before release)~~
- [x] Clean up the changelog (regroup in subsections)  #3370 
- [x] Make sure all major features are documented (including new CLI, and venv creation).  
       - https://github.com/pyodide/pyodide/pull/3367
- [x]  #3349
- [x] Add release CI for pyodide-py https://github.com/pyodide/pyodide/issues/1839

__Things that are not going be included in 0.22__

- Update to Python 3.11: #3252
- Bundle the standard library in a zip file: #3166
- #3269
- libpyodide.a #3335

**Comment by hoodmane** [comment]
Thanks @ryanking13!

**Comment by rth** [comment]
> More general unvendoring mechanism #3092

IMO this could wait for 0.23.

The other things I added to the 0.22 TODO list is,
>  Clean up the changelog (regroup in subsections)
> Make sure all major features are documented (including new CLI, and venv creation).

**Comment by hoodmane** [comment]
We should go ahead and make the release whenever someone gets to it.
