### ISSUE TITLE
TODO list for 0.23.0 alpha release

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3410]
The next Pyodide 0.23.0 release will contain several big user-facing changes, including Python3.11 update. So we are thinking of releasing 0.23.0a0 soon so that users can test it.

This issue is to list up things we want to include (= things that need to be done) in the 0.23.0 alpha release.

- [x] Python 3.11 update https://github.com/pyodide/pyodide/pull/3252
  - It would be nice to have a proper benchmark to test speedup (https://github.com/pyodide/pyodide/issues/2467), though it is not necessary for alpha release.
- [ ] vendoring standard library into a zip file
- [ ] distributing .pyc compiles source
- ...

**Comment by hoodmane** [comment]
Maybe let's just release an alpha after we land #3252.

**Comment by hoodmane** [comment]
We can make another with the other features later.

**Comment by rth** [comment]
Sounds good to me.

**Comment by ryanking13** [comment]
Sounds good to me too.

**Comment by MRigal** [comment]
Probably part/assign to https://github.com/pyodide/pyodide/milestone/14
