### ISSUE TITLE
llvm-flang + scipy progress tracker

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#5268]
This issue is to track the progress in building Fortran packages using llvm-flang. The primary target is Scipy.

- llvm-flang
  - [x] included in the LLVM toolchain.
 
- WASM backend for llvm-flang
  - [ ] not officially supported (https://discourse.llvm.org/t/flang-web-assembly/61607).
  - [x] r-wasm team forked llvm and enabled WASM backend (https://github.com/r-wasm/flang-wasm)
  - [x] I used that fork to make a prebuilt binary using the same emscripten version in Pyodide (https://github.com/ryanking13/flang-llvm-emscripten)

- llvm-flang in Emscripten toolchain
  - [ ] flang is not integrated in the Emscripten toolchain, obviously, as no WASM backend supported yet.

- meson
  - [x] Added initial support for llvm-flang since v1.6.0 (https://github.com/mesonbuild/meson/pull/13323)
- scipy
  - [x] https://github.com/scipy/scipy/pull/21917

---

Error logs

__2024/12/20__

> LLVM ERROR: SmallVector unable to grow. Requested capacity (18446744072885119280) is larger than maximum value for size type (4294967295)

Hitting this error when compiling `PROPACK` codes. The each number in the log represents `2^64` and `2^32`, so it is certain that somehow it is related to the 32-bit, 64-bit variables (architectures), but it is unclear how to handle it.

<details><summary>Full error log</summary>
<p>

LLVM ERROR: SmallVector unable to grow. Requested capacity (18446744072885119280) is larger than maximum value for size type (4294967295)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /src/emsdk/emsdk/upstream/emscripten/flang-new -fc1 -triple wasm32-unknown-emscripten -emit-obj -I scipy/sparse/linalg/_propack/liblib__spropack.a.p -I scipy/sparse/linalg/_propack -I ../scipy/sparse/linalg/_propack -D NDEBUG -U _OPENMP -mrelocation-model pic -pic-level 2 -target-cpu generic -fversion-loops-for-stride -module-dir scipy/sparse/linalg/_propack/liblib__spropack.a.p -resource-dir /src/emsdk/emsdk/upstream/lib/clang/19 -mframe-pointer=none -O3 -o scipy/sparse/linalg/_propack/liblib__spropack.a.p/PROPACK_single_printstat.F.o -x f95-cpp-input ../scipy/sparse/linalg/_propack/PROPACK/single/printstat.F
1.	Program arguments: 
 #0 0x000055dbca162673 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x105a673)
 #1 0x000055dbca160ecc llvm::sys::RunSignalHandlers() (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1058ecc)
 #2 0x000055dbca161a71 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f5cffc44050 (/lib/x86_64-linux-gnu/libc.so.6+0x3c050)
 #4 0x00007f5cffc92e2c (/lib/x86_64-linux-gnu/libc.so.6+0x8ae2c)
 #5 0x00007f5cffc43fb2 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3bfb2)
 #6 0x00007f5cffc2e472 abort (/lib/x86_64-linux-gnu/libc.so.6+0x26472)
 #7 0x000055dbca12d523 llvm::report_fatal_error(llvm::Twine const&, bool) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1025523)
 #8 0x000055dbca130836 unsigned long getNewCapacity<unsigned int>(unsigned long, unsigned long, unsigned long) (.constprop.0) SmallVector.cpp:0:0
 #9 0x000055dbca1309a6 llvm::SmallVectorBase<unsigned int>::grow_pod(void*, unsigned long, unsigned long) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x10289a6)
#10 0x000055dbc9f1d6fb main (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xe156fb)
#11 0x000055dbcb0ab5f1 llvm::AsmPrinter::doFinalization(llvm::Module&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1fa35f1)
#12 0x000055dbcc5ae1d6 llvm::FPPassManager::doFinalization(llvm::Module&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x34a61d6)
#13 0x000055dbcc5b4444 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x34ac444)
#14 0x000055dbca4cb5f9 Fortran::frontend::CodeGenAction::executeAction() (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x13c35f9)
#15 0x000055dbca184ff9 Fortran::frontend::FrontendAction::execute() (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x107cff9)
#16 0x000055dbca17df8b Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1075f8b)
#17 0x000055dbca188569 Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1080569)
#18 0x000055dbca0a86a3 fc1_main(llvm::ArrayRef<char const*>, char const*) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xfa06a3)
#19 0x000055dbc9f1dae0 main (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xe15ae0)
#20 0x00007f5cffc2f24a (/lib/x86_64-linux-gnu/libc.so.6+0x2724a)
#21 0x00007f5cffc2f305 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27305)
#22 0x000055dbca0a7b75 _start (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xf9fb75)
 #0 0x000055dbca162673 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x105a673)
 #1 0x000055dbca160ecc llvm::sys::RunSignalHandlers() (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1058ecc)
 #2 0x000055dbca161a71 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f5cffc44050 (/lib/x86_64-linux-gnu/libc.so.6+0x3c050)
 #4 0x00007f5cffc92e2c (/lib/x86_64-linux-gnu/libc.so.6+0x8ae2c)
 #5 0x00007f5cffc43fb2 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3bfb2)
 #6 0x00007f5cffc2e472 abort (/lib/x86_64-linux-gnu/libc.so.6+0x26472)
 #7 0x000055dbca12d523 llvm::report_fatal_error(llvm::Twine const&, bool) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1025523)
 #8 0x000055dbca130836 unsigned long getNewCapacity<unsigned int>(unsigned long, unsigned long, unsigned long) (.constprop.0) SmallVector.cpp:0:0
 #9 0x000055dbca1309a6 llvm::SmallVectorBase<unsigned int>::grow_pod(void*, unsigned long, unsigned long) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x10289a6)
#10 0x000055dbc9f1d6fb main (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xe156fb)
#11 0x000055dbcb0ab5f1 llvm::AsmPrinter::doFinalization(llvm::Module&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1fa35f1)
#12 0x000055dbcc5ae1d6 llvm::FPPassManager::doFinalization(llvm::Module&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x34a61d6)
#13 0x000055dbcc5b4444 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x34ac444)
#14 0x000055dbca4cb5f9 Fortran::frontend::CodeGenAction::executeAction() (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x13c35f9)
#15 0x000055dbca184ff9 Fortran::frontend::FrontendAction::execute() (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x107cff9)
#16 0x000055dbca17df8b Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1075f8b)
#17 0x000055dbca188569 Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0x1080569)
#18 0x000055dbca0a86a3 fc1_main(llvm::ArrayRef<char const*>, char const*) (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xfa06a3)
#19 0x000055dbc9f1dae0 main (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xe15ae0)
#20 0x00007f5cffc2f24a (/lib/x86_64-linux-gnu/libc.so.6+0x2724a)
#21 0x00007f5cffc2f305 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27305)
#22 0x000055dbca0a7b75 _start (/src/emsdk/emsdk/upstream/emscripten/flang-new+0xf9fb75)
flang: error: unable to execute command: Aborted
flang: error: flang frontend command failed due to signal (use -v to see invocation)
flang-new version 19.0.0git (https://github.com/ryanking13/llvm-project ad07d10d693c992bcf365d5b469af44e614f2a7b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /src/emsdk/emsdk/upstream/emscripten
flang: note: diagnostic msg: 

</p>
</details>

**Comment by agriyakhetarpal** [comment]
Thanks for starting this! 🚀

**Comment by agriyakhetarpal** [comment]
What happens if we comment-out PROPACK and its related extension modules that rely on it?

**Comment by ryanking13** [comment]
> What happens if we comment-out PROPACK and its related extension modules that rely on it?

Good point. When I remove `PROPACK` from the build target, the same error happens in another module:

```
FAILED: scipy/stats/_mvn.cpython-312-wasm32-emscripten.so.p/mvndst.f.o 
/tmp/tmpzicksovk/flang -Iscipy/stats/_mvn.cpython-312-wasm32-emscripten.so.p -Iscipy/stats -I../scipy/stats -I../../../../../../tmp/build-env-nn29cip4/lib/python3.12/site-packages/numpy/_core/include -I../../../../../../tmp/build-env-nn29cip4/lib/python3.12/site-packages/numpy/f2py/src -Iscipy/lib_fortranobject.a.p -I/src/packages/.libs/include -I/src/cpython/installs/python-3.12.7/include/python3.12 -I/usr/local/include/python3.12 -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -O3 -fPIC -module-dir scipy/stats/_mvn.cpython-312-wasm32-emscripten.so.p -o scipy/stats/_mvn.cpython-312-wasm32-emscripten.so.p/mvndst.f.o -c ../scipy/stats/mvndst.f
LLVM ERROR: SmallVector unable to grow. Requested capacity (18446744072436006608) is larger than maximum value for size type (4294967295)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /src/emsdk/emsdk/upstream/emscripten/flang-new -fc1 -triple wasm32-unknown-emscripten -emit-obj -I scipy/stats/_mvn.cpython-312-wasm32-emscripten.so.p -I scipy/stats -I ../scipy/stats -I ../../../../../../tmp/build-env-nn29cip4/lib/python3.12/site-packages/numpy/_core/include -I ../../../../../../tmp/build-env-nn29cip4/lib/python3.12/site-packages/numpy/f2py/src -I scipy/lib_fortranobject.a.p -I /src/packages/.libs/include -I /src/cpython/installs/python-3.12.7/include/python3.12 -D NDEBUG -mrelocation-model pic -pic-level 2 -target-cpu generic -fversion-loops-for-stride -module-dir scipy/stats/_mvn.cpython-312-wasm32-emscripten.so.p -resource-dir /src/emsdk/emsdk/upstream/lib/clang/19 -mframe-pointer=none -O3 -o scipy/stats/_mvn.cpython-312-wasm32-emscripten.so.p/mvndst.f.o -x f95-cpp-input ../scipy/stats/mvndst.f
1.	Program arguments: 
```

So, it seems like it is generally happening in several modules.

**Comment by agriyakhetarpal** [comment]
I see. Question: I think we would need to build OpenBLAS, LAPACK, etc. that we need for SciPy first, without `f2c`ing them, like our friends at `emscripten-forge` have done?

**Comment by agriyakhetarpal** [comment]
I see. Question: would we need to build OpenBLAS, LAPACK, etc. that we need for SciPy first, without `f2c`ing them, like our friends at `emscripten-forge` have done?

**Comment by ryanking13** [comment]
> I see. Question: would we need to build OpenBLAS, LAPACK, etc. that we need for SciPy first, without f2cing them, like our friends at emscripten-forge have done?

Indeed, building openblas with Fortran code and dropping `libf2c` would also be needed. I don't think it is related to the current build errors, but we should handle them too.

**Comment by lesteve** [comment]
Nice, I wasn't aware of this work and have wondered in the past what prevented Pyodide to do something closer to that r-wasm is doing (even if forking llvm seems kind of scary ...).

**Comment by agriyakhetarpal** [comment]
Some updates:
- With LLVM 20, `flang-new` has dropped the suffix – it is now labelled as just `flang`.
- R has been packaged (see https://github.com/emscripten-forge/recipes/issues/1050), which also required Netlib BLAS and LAPACK (with minimal modifications and without `f2c`-related patches; see https://github.com/emscripten-forge/recipes/pull/1284).
- Our friends at `emscripten-forge` are trying out SciPy here: https://github.com/emscripten-forge/recipes/pull/1851. I have to note that they target Emscripten 3.1.73, while we will target 4.0.1 in the coming days (#5332), most likely before we release 0.28.

Maybe LLVM 20.1.0 that was released earlier this week won't have the above "SmallVector unable to grow" issue we faced above? Though, I still think that is a misconfigured option somewhere. In the meantime, I'll return to #5297.

**Comment by ryanking13** [comment]
That's great news! Thanks for the update, Agriya, and I am happy that other folks are experimenting with llvm flang, as I am not really an expert on Fortran.

**Comment by agriyakhetarpal** [comment]
I'm not sure if our emscripten-forge friends completed compiling SciPy with LLVM Flang, as I see that emscripten-forge/recipes#1851 was later superseded by emscripten-forge/recipes#2044; which also used `f2c`. However, they succeeded in compiling OpenBLAS using Flang: https://github.com/emscripten-forge/recipes/tree/178963dc30dd3592541a911bdf498d71ba36257e/recipes/recipes_emscripten/openblas-flang. It is a standalone recipe and is not currently used as a dependency for any other dependencies – it has probably been kept for later.

At least this part of the issue description above:

> WASM backend for llvm-flang

is being worked on in conda-forge/flang-feedstock#67, and these patches were ported to emscripten-forge and used for OpenBLAS-FLang.

Perhaps either LLVM Flang 20 would work for SciPy and we won't get internal LLVM errors as previously noticed, or we will need to address various aspects from the ground up here; right from the OpenBLAS compilation, removal of `void`s to `int`s conversions and the like, compiling CLAPACK, all of the bits we do to punch `f2c` at the Fortran subpackages (i.e., the pywasmcross and `_scipy_fixes` hacks) and so on.

We should keep in mind that the eventual goal is to send the patches to SciPy upstream and contribute to an out-of-tree CI job, if feasible, at some point. Therefore, even if we manage to get the compilation working, the aim is also to reduce the number of patches so that an out-of-tree job is closer in reality. In [pyodide/pyodide-recipes#141](https://github.com/pyodide/pyodide-recipes/pull/141), I removed five out of the eighteen patches and added one, bringing the number to fourteen.

**Comment by ilayn** [comment]
We completed the translation work in SciPy scipy/scipy#18566 apart from a single module (`scipy.odr` which is deprecated and will be removed in v1.19). 

Starting from SciPy 1.19, it will be Fortran-free. Hopefully it will make your lives a bit easier.

**Comment by ryanking13** [comment]
@ilayn Thanks for the update! That's the best news I've heard.

**Comment by agriyakhetarpal** [comment]
I think it is the right time to close this issue now and move the conversation to the newer issue I have opened about a Fortran-free future: https://github.com/pyodide/pyodide-recipes/issues/604. Thanks for the initial experiments with using LLVM Flang, @ryanking13! I am a bit disappointed that we were not come to fruition about them, but happy that even SciPy doesn't need to deal with a Fortran compiler.

**Comment by ryanking13** [comment]
yeah, supporting scipy was kind of our only reason for us to test FORTRAN to Wasm compiler. As scipy is dropping fortran, I think we can close this.
