### ISSUE TITLE
Better integration with conda/conda-forge for building packages

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#795]
The idea to rely on conda-forge for building Python packages to WebAssembly has been mentioned for a while now (https://github.com/iodide-project/pyodide/issues/38#issuecomment-410270067, https://github.com/conda/conda/issues/7619, https://github.com/regro/cf-scripts/issues/1052#issuecomment-651995625), and in this issue I wanted start a discussion about current situation and existing challenges to move in that direction from the perspective of pyodide, as I understand it (please correct me if needed).

First the main motivation is that the present way of building all the packages in one repo is not sustainable with the increase of the number of packages and the associated increase in CI time. To resolve this we would need significant development resources, which we don't have. Even if we did, it would amount to doing many things (including a community) that already exist and work great at conda-forge, which wouldn't make sense.

Now as to challenges (it's a long post),

### 1. Updating emscripten

With a single repo it's relatively fast to rebuild all packages with a different version of the emsdk toolchain (emscripten, binaryen, ..) or different options. We currently still have a couple of patches applied to emscripten, and we also ideally need to update emscripten frequently to benefit from improvements and fixes (currently 1.5 years late with respect to the latest release, unfortunately).  In conda-forge rebuilding all the packages with a new compiler would take longer (though this got better recently https://github.com/regro/cf-scripts/issues/1052#issuecomment-652003811). Also the use-case where a) we update emscripten version b) some package fails to build c) we have to go back and change some global emscripten settings would really be unpractical I think.

This would hopefully become less of an issue with time as emscripten becomes more and more stable, but it's still an issue now (see e.g. https://github.com/iodide-project/pyodide/pull/480#issuecomment-635823062)
     
### 2. Build approach

The cross-compilation of scientific Python packages (based on distutils) is difficult (https://github.com/scipy/scipy/issues/8571, https://github.com/numpy/numpy/issues/17620) as far as I understand, even on Linux between different architectures.

I'm not sure if this was the reason, but pyodide doesn't do cross-compilation in the classical sense. Instead it compiles the package with the host compilers, stores a log of all executed compilation commands and re-run those commands with the emscripten compiler.

### 3. Shared package specifications

Package specifications where chosen as close as possible to the `meta.yaml` in conda, and hopefully soon the package index will also use the same format (https://github.com/iodide-project/pyodide/issues/791)

### 4. Artifacts format

Currently each package consist of 2 separate (.data, .js) files which we distribute via jsDelivr. Those would probably not fit as conda artifacts, which would mean that we likely need to handle some of this in any case.

### 5. Dependency resolution in the browser

There are two use cases for pyodide,
 1. interactive (notebooks, etc) where having a dependency resolver in the browser (e.g. mamba) would be great.
 2. python applications, where dependencies are known in advance, and we certainly don't want to do dependency resolution at each page load. There having a precomputed list of packages is likely the way to go.

Either way we also need to install pure python wheels (from PyPi or other custom location), so we still have this duality between conda/pyodide packages and Python wheels as well. Meaning we have to maintain a minimalistic pip ([micropip](https://pyodide.readthedocs.io/en/latest/micropip-api/micropip.install.html#micropip.install)) in pyodide.

I haven't followed close WebAssembly related developments at conda-forge, maybe I am missing something.

cc @wolfv @jakirkham

**Comment by isuruf** [comment]
We have cross compilation support in conda-forge. We cross compiled numpy, scipy, matplotlib for `osx-arm64` platform. First thing to do would be to add a platform to `conda` and `conda-build`. something like `wasm`.

**Comment by jakirkham** [comment]
Thanks for writing this up Roman! 😄

This sounds like a good summary to me. I think going from 3 to 4 has been the step I've always been pretty fuzzy on (though I'm guessing you know this pretty well 😉). How does one turn a Conda package tarball into something that pyodide can use? Where do these get hosted?

As Isuru's point about adding a platform in Conda, I think this was the idea behind issue ( https://github.com/conda/conda/issues/7619 ), but may be missing things here.

One other thing worth discussing is over time LLVM's ability to build WASM binaries has grown. Does it make sense to start using that or is Emscripten still needed for some things? The one thing that I recall use to be a stumbling block was a `libc` implementation for WASM. Though it looks like [this has since been solved]( https://github.com/WebAssembly/wasi-libc )? In which case maybe building this `libc` binary gives us enough to get started?

**Comment by rth** [comment]
Thanks for the feedback @isuruf @jakirkham ! Great to know that cross compilation works conda-forge.

> I think going from 3 to 4 has been the step I've always been pretty fuzzy on

As far as I understand those `(.data, .js)` are files to unpack in the virtual filesystem and associated unpacking instructions (cf [emscripten docs](https://emscripten.org/docs/porting/files/packaging_files.html#packaging-using-the-file-packager-tool)). We could potentially repackage them into a single file during build then separate them on the client side. 

The question for me is more is the conda artifacts really the best format for distributing such files (which were not optimized for this use case). Maybe there are some other apporaches in the JS/WASM ecosystem that would be better. I haven't studied the question in detail so far.

For now we put the artifacts in an S3 under versioned paths and CDN proxy it by JsDelivr, which allows for a lot flexibility.


> One other thing worth discussing is over time LLVM's ability to build WASM binaries has grown. Does it make sense to start using that or is Emscripten still needed for some things? 

Absolutely, it would be good to revisit if the situation evolved much since the discussion in https://github.com/conda/conda/issues/7619

> The one thing that I recall use to be a stumbling block was a libc implementation for WASM. Though it looks like this [has since been solved](https://github.com/WebAssembly/wasi-libc)? 

The link you provide is for WASI or outside of the browser, as far as I understand though? Within the browser, we still need an in-memory filesystem (currently [provided by emscripten](https://emscripten.org/docs/api_reference/Filesystem-API.html#file-system-api)) as CPython wouldn't be very useful without it. For instance Rust can be easily compiled to WASM (without emscripten), but then you cannot do [filesystem I/O](https://rustwasm.github.io/docs/book/reference/add-wasm-support-to-crate.html#adding-support-for-webassembly) at least as indicated in the reference materials. Maybe there are indeed lighter projects providing the necessary abstractions, it could be worth checking.

**Comment by wolfv** [comment]
I have just updated binaryen (https://github.com/conda-forge/binaryen-feedstock/pull/38) and added an Emscripten recipe to conda-forge. With those two things we could be ready to explore these ideas.

I'd be happy to integrate cross-compilation to javascript "natively" into boa so that it becomes very straight-forward ... although I am not sure how simple that will be.

I think conda is more than the package format, and that should not be the thing holding us up -- we can easily create a new, more web-optimized package format (different or no compression etc.) if we have to.
What I think is great is the community, the available packages, automation, and the build infrastructure by conda-forge etc.

Regarding libc, I was under the impression that emscripten did some magic to get me a libc :) in general, emscripten seemed to work quite smoothly.

Personally, I'd be quite interested in getting the packages in [boa-forge](https://github.com/mamba-org/boa-forge) to compile to see if we can bootstrap a wasm-micromamba.

**Comment by rth** [comment]
> I have just updated binaryen (conda-forge/binaryen-feedstock#38) and added an Emscripten recipe to conda-forge

If you don't use [emsdk](https://github.com/emscripten-core/emsdk) you might need to [package it manually](https://github.com/emscripten-core/emscripten/blob/master/docs/packaging.md) which doesn't sound that simple (but they did it in Homebrew)

**Comment by wolfv** [comment]
It's not very difficult to package emscripten - I have a working recipe that I have been using to build wasm conda packages.
It's surprisingly simple, and I already got working libraries for a bunch of compression algorithms that are of interest to us, as well as the first half of libsolv (I managed to run it to parse conda repodata.json into a `solv` file. 

So it all sounds quite doable (including running a micromamba in the browser). For that we'd need to rewrite mamba a bit though, to use the emscripten Fetch and FileSystem APIs instead of curl. We could give it a shot though.
Alternatively we could figure out how make a mamba-derivative that one can feed repodata.json through javascript and that spits out the packages to download, and then unpacks that using a different entrypoint or something like that...

@rth you might know better how to do this!

We could also make sure to only support one of the two (three, actually) compression algorithms that conda is using currently (e.g. allow only `.tar.bz2` packages?!).
I have a small issue compiling zstd, it tells me that `wasm-ld: error: initial memory too small, 38821440 bytes needed` (any ideas, @rth ?)

I can upload the recipes I have soon. Would be cool to have a collaboration for this!

**Comment by rth** [comment]
Sorry for slow response @wolfv 

> It's not very difficult to package emscripten - I have a working recipe that I have been using to build wasm conda packages.

That's great!

> For that we'd need to rewrite mamba a bit though, to use the emscripten Fetch and FileSystem APIs instead of curl.

Indeed. In pyodide, we just mount the filesystem and then it can be interacted with directly from Python. However for interacting with remote URLs one indeed need to rewrite everything with Web APIs (e.g. [`pyodide.open_url`](https://github.com/iodide-project/pyodide/blob/f7adad7eb30a54ce4ed82e6e15950931c77dd1cc/src/pyodide.py#L14))

> I have a small issue compiling zstd, it tells me that wasm-ld: error: initial memory too small, 38821440 bytes needed 

Likely https://github.com/emscripten-core/emscripten/blob/1216d230eac6a335f1397f4ab1d2bf297113633b/src/settings.js#L152 needs to be increased with a env variable.

> Would be cool to have a collaboration for this!

Yes, that would be great. For pyodide that would mean incrementally get closer to the conda-forge apporach and possibly start using some of the tooling.

One thing where I would be interested in your feedback is assuming python packages are built with emscripten on conda-forge, would the current way of detecting it at build time in setup.py is appropriate (currently via the [`PYODIDE_PACKAGE_ABI` env variable](https://pyodide.readthedocs.io/en/latest/faq.html#how-to-detect-that-code-is-run-with-pyodide)) or would you propose some other solution? It would be good to agree on that before that variable end up in too many upstream projects. Or do you think that just a env variable for cross-compilation (e.g. as done by @isuruf in   https://github.com/scikit-learn/scikit-learn/pull/18884) would be enough?

**Comment by wolfv** [comment]
Are you interested in helping me to bootstrap some "emscripten" enabled recipes? I can create a repo, and we could run a Azure pipeline to build a couple of wasm compiled conda packages.

**Comment by rth** [comment]
@wolfv yes, we could try to experiment there.

**Comment by wolfv** [comment]
Ok, I'll have to get emscripten on conda-forge first, then I'll set it up.

**Comment by rth** [comment]
So overall emscripten-forge went this road, we are more focused on producing wheels with PyPA / cibuildwheel tooling. But we can certainly open more specific issues about ways to share some of the tools or approaches.

**Comment by westurner** [comment]
Here are the current docs. Should they mention *MambaLite* – which installs packages from emscripten-forge instead of conda-forge, which doesn't host WASM packages – as a third-party tool 
https://pyodide.org/en/stable/usage/loading-packages.html :

> ### Loading packages
> Only the Python standard library is available after importing Pyodide. To use other packages, you’ll need to load them using either:
> 
> - `pyodide.loadPackage` for packages built with Pyodide, or
> 
> - `micropip.install` for pure Python packages with wheels available on PyPI or from other URLs.
>
> **Note**: micropip can also be used to load packages built in Pyodide (in which case it relies on pyodide.loadPackage).
>
> If you use `pyodide.loadPackagesFromImports` Pyodide will automatically download all packages that the code snippet imports. This is particularly useful for making a repl since users might import unexpected packages. At present, `loadPackagesFromImports` will not download packages from PyPI, it will only download packages included in the Pyodide distribution. See *Packages built in Pyodide* to check the full list of packages included in Pyodide.

- [ ] DOC: Describe & link to `mambalite`
- [ ] DOC,SEC: compare package signing and verification mechanisms
  - [ ] Would sigcheck + W3C Verified Claims + a Blockchain for signed artifact hashes partially solve for {pip, conda, and MambaLite,} packages?

"Mamba meets JupyterLite" (2022-07) 
https://blog.jupyter.org/mamba-meets-jupyterlite-88ef49ac4dc8

> - Binderlite: A JupyterLite / emscripten-forge powered version of Binder

- emscripten-forge/recipes/python
  https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/python/recipe.yaml
  - conda-forge python has different patches:
    https://github.com/conda-forge/python-feedstock/blob/main/recipe/meta.yaml
  - https://conda-forge.org/docs/maintainer/knowledge_base.html
  - https://conda-forge.org/docs/maintainer/knowledge_base.html#security-considerations-for-conda-forge-builds
  - NumPy, CUDA,
- emscripten-forge/recipes/.github/workflows/build_recipes.yaml
  https://github.com/emscripten-forge/recipes/blob/master/.github/workflows/build_recipes.yaml
- https://github.com/emscripten-forge/recipes/blob/main/testing/browser_test_package.py
- When the bokeh feedstock went `noarch`, it became possible to host it on and install it from conda-forge: 
  https://github.com/conda-forge/bokeh-feedstock/pull/76/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a

- conda-forge has a more consistent set of compilers and build dependencies like CUDA and MKL (NumPy,): 
https://conda-forge.org/docs/maintainer/infrastructure.html?highlight=smith#compilers-and-runtimes
  - https://conda-forge.org/docs/user/announcements.html
    - Conda-forge announces changes to compilers and runtimes in the announcements 

From https://github.com/emscripten-forge/empack :

> Tools to pack a conda / mamba environment into a JS & WASM bundle
>
> ```bash
empack pack env --env-prefix /path/to/env --outname python_data  --config /path/to/config.yaml
```
>
> This will generate two files `python_data.js` and `python_data.data` that you can use in the browser. A sample config is located in `tests/empack_test_config.yaml`

@DerThorsten 
But where is the source and recipe/feedstock for MambaLite?
- https://github.com/mamba-org/mamba
  - https://github.com/conda/conda
  - "mambaforge" https://github.com/conda-forge/miniforge#mambaforge

**Comment by DerThorsten** [comment]
picomamba /mamba-lite is here:
https://github.com/mamba-org/picomamba
But this is not yet working since the conda-noarch pkgs are missing some CORS headers to download them in the browser.

**Comment by westurner** [comment]
- /? libsolv # mamba, dnf, dnf5,
  - `def install_noarch_package()`
    https://github.com/mamba-org/picomamba/blob/d15420d2a2cf1cabf19da42e4c7a1734a5c4c46b/python/module/picomamba/picomamba.py#L176-L189

- [ ] SEC?,ETC: conda-forge noarch CORS headers
  - [ ] add headers w/ e.g. cloudflare {_, CDN, Pages}
- [ ] $$$: emscripten-forge, conda-forge, **NumFOCUS**: How to estimate donated bandwidth costs for Ctrl-R from WASM for schools and patient data engineers
      - Do HTTP/3 & caching like CF or pay CF
      

- How to apply to NumFOCUS
  https://numfocus.org/projects-overview
  - /CC @aterrel re: Building JupyterLite+ for hosting on CDN'd RTD & WASM & the *new* local File System Access API & package dependency resolution
    - my guess what Andy's [...]
      - "When does my project need to become a legal entity?" 
        https://github.com/aterrel/fiscal-sponsorship-talk/blob/master/fiscal-sponsorship.ipynb
- https://numfocus.org/community/mission :
  > Our Mission
  > The mission of NumFOCUS is to promote open practices in research, data, and scientific computing by serving as a fiscal sponsor for open source projects and organizing community-driven educational programs.
  > 
  > NumFOCUS is a 501(c)(3) public charity in the United States.
  > 
  > Our Vision
  > NumFOCUS envisions an inclusive scientific and research community that utilizes actively supported open source software to make impactful discoveries for a better world


FROM https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository :

> Here's an example FUNDING.yml file:
> ```YAML
> github: [octocat, surftocat]
> patreon: octocat
> tidelift: npm/octo-package
> custom: ["https://www.paypal.me/octocat", octocat.com]
> ```

**Comment by westurner** [comment]
From https://twitter.com/simonw/status/1559969074607599617 w/ @simonw re: WASM package security controls and the *just in a browser tab* software supply chain :

> I added plugin support to Datasette Lite - my distribution of @datasetteproj that runs entirely in the browser using Python and SQLite compiled to WebAssembly
>
> You can now install extra plugins by adding `?install=plugin-name` to the Datasette Lite URL

From https://simonwillison.net/2022/Aug/17/datasette-lite-plugins/ :

> Since the `?install=` parameter is being passed directly to `micropip.install()` you don’t even need to provide names of packages hosted on PyPI—you could instead provide the URL to a wheel file that you’re hosting elsewhere.

> This means you can use `?install=` as a code injection attack—you can install any Python code you want into the environent. I think that’s fine—the only person who will be affected by this is the user who is viewing the page, and the lite.datasette.io domain deliberately doesn’t have any cookies set that could cause problems if someone were to steal them in some way.

FWIU packages are persisted w/ SQLite in WASM, *per-request*?

- HTTP If-Modified-Since
- HTTP Caching ETAGs: ./filen.ame.ETAG, 
- https://en.wikipedia.org/wiki/Content_delivery_network#Content_networking_techniques
- https://en.wikipedia.org/wiki/InterPlanetary_File_System#Applications #Malware
  - Cloudflare HTTP IPFS gateway 
    > https://cloudflare-ipfs.com/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/
- https://docs.skynetlabs.com/developer-guides/moving-from-ipfs-to-skynet
  > - both projects use the idea of "pinning" data to make it available on the network, although the exact mechanics differ for each project

"Pypi.org is running a survey on the state of Python packaging" (2022)
https://news.ycombinator.com/item?id=32751603

- https://westurner.github.io/hnlog/#comment-30687197 ... https://westurner.github.io/hnlog/#comment-32760170

  - ~~GPG~~ (\*)
  - ~~Wheel signatures~~
  - TUF (PyPi, Docker Notary, Fuschia, Conda,)
  - Sigstore (CNCF,)
  - Conda package signatures (TUF\`)
    - https://www.anaconda.com/blog/conda-signature-verification (2021)
    - https://github.com/conda/conda-content-trust
  - WASM package signatures
    - Web Bundles & Signed HTTP Exchanges
      https://web.dev/web-bundles/
      > HTTP resources in a Web Bundle are indexed by request URLs, and can optionally come with signatures that vouch for the resources. Signatures allow browsers to understand and verify where each resource came from, and treats each as coming from its true origin. This is similar to how Signed HTTP Exchanges, a feature for signing a single HTTP resource, are handled
  - W3C DIDs for package URIs, authors
    - The pk from an sk/pk keypair can be the DID identifier, with a namespace URI
  - .
  - Declarative JSON / JSONLD metadata for CycloneDX SBOM Software Bill of Materials

**Comment by rth** [comment]
> Should they mention MambaLite

Happy to add emscripten-forge under [related projects](https://pyodide.org/en/stable/project/related-projects.html) (please open a PR) however I don't this belongs, at least for now, in the main section on how to install packages (which is already rather confusing ). They are alternative distributions. For instance, you won't see in the pip documentation, "well you can also install this with conda", or conda-forge advertising to use homebrew in the official documentation.

Though in any case, it would be good to figure out binary compatibility first between Pyodide and emscripten-forge packages

Also, I'm very happy to chat @DerThorsten and see points on which we could work together. For instance, we are currently unvendoring micropip from the monorepo so it's easier to reuse if necessary https://github.com/pyodide/pyodide/issues/3093

My point in closing this issue was that we can open more specific discussion points, but we can also continue the discussion here if you prefer.


@westurner thank you for your comments with this information, but I'm not entirely sure what you proposing though :)

**Comment by DerThorsten** [comment]
> Though in any case, it would be good to figure out binary compatibility first between Pyodide and emscripten-forge packages
agreed, that would be a great first step!

> Also, I'm very happy to chat @DerThorsten and see points on which we could work together. For instance, we are currently unvendoring micropip from the monorepo so it's easier to reuse if necessary #3093

Would be happy to work together more!

**Comment by westurner** [comment]
This issue having been closed, it seemed out of the way from actual progress that it might be holding up.

There are many systems for package metadata and signed cryptographic manifests (some with per-file hash checksums). Where we have functional overlap and duplication of effort, there is potential for security vulnerability.

How should pyodide's build change to better integrate with conda-forge (and emscripten-forge)? Hopefully the aforementioned tools copy the manifest signatures over when re-packing and re-hosting.

When pyodide / micropip was written:
- pip didn't have end-to-end-package signatures (~GPG w/o keyserver~)
- conda didn't have end-to-end package signing
- GPG asc signature upload support may have already been removed from warehouse (the application that hosts PyPI)
- TUF server signatures were not yet implemented on PyPI
- (TUF author signatures are not yet implemented on PyPI (end-to-end package signing))
- Signed HTTP Exchanges (SXG) & Web Bundles weren't yet finalized (could be used to secure WASM packages)
- HTTP Subresource Integrity (SRI):
  ```html
  <script src="https://cdn.example.com/app.js"
         integrity="sha384-+/M6kredJcxdsqkczBUjMLvqyHb1K/JThDXWsBVxMEeZHEaMKEOEct339VItX1zB"
         crossorigin="anonymous"></script>
  ```

There are many opportunities to drop the ball in build systems and application dependency composition; DevSecOps for software supply chain security.
How can pyodide require package signatures in order to prevent (widescale) exploitation of

**Comment by rth** [comment]
Yes, these are good questions. Would you mind though opening a separate issue about end-to-end package signing, as it's a very specific technical point that it would be better to discuss separately from this very general issue? 

In our case, as compared to pip or conda,  the attack surface is very much reduced due to the browser sandbox. But yes, the security story can certainly be improved and there is still the usage in Node which doesn't provide a sandbox.

> How should pyodide's build change to better integrate with conda-forge (and emscripten-forge)?

Short answer is we don't plan to integrate with conda forge anymore. emscripten-forge is working on that. For Pyodide we are going for better integration with PyPI, PyPA tooling, cibuildwheel etc.

**Comment by westurner** [comment]
Are there projections as to what the load impact on PyPI and it's CDN
expenses will be from WASM apps pulling dependencies on every run?
https://pypi.org/sponsors/

- "[Discussions on Python.org] [Packaging]
  Draft PEP: PyPI cost solutions: CI, mirrors, containers, and caching to
scale"

https://discuss.python.org/t/draft-pep-pypi-cost-solutions-ci-mirrors-containers-and-caching-to-scale/3681
  https://groups.google.com/g/pypa-dev/c/Pdnoi8UeFZ8

- Pip downloads wheels for every CI build and deployment
- Pip does not download wheels for every process invocation
- Micropip downloads wheels for every page load process invocation from PyPI
- MambaLite downloads empkg rebuilds of conda packages unless there's a
noarch conda package, but their HTTP headers aren't setup to CDN for
"download every package on every process invocation / page load"

**Comment by westurner** [comment]
(I must have confused "building pyodide" / "building pyodide packages like
conda-forge / emscripten-forge"
with "just have piplite solve and install the dependency graph from PyPI
for every page load")

**Comment by hoodmane** [comment]
@westurner I opened #3127 for CDN resource usage discussion.

**Comment by westurner** [comment]
Thanks

**Comment by yuvipanda** [comment]
Just as an FYI, I opened https://github.com/conda-forge/staged-recipes/pull/20961 adding micropip as a conda-forge noarch package, which should (I hope? idk :D) allow emscriptenforge and micropip to be used together like how conda-forge and pip can be used together.

**Comment by wolfv** [comment]
awesome @yuvipanda – that's great news. It didn't even come to my mind to just add it to conda-forge :)

**Comment by westurner** [comment]
@yuvipanda 
- https://github.com/pyodide/micropip/issues/82

**Comment by RemDelaporteMathurin** [comment]
Hi @rth I was curious to know what was the status of supporting conda-forge packages with pyodide! :-)

**Comment by westurner** [comment]
jupyterlite-xeus:
https://github.com/jupyterlite/xeus :

> The core feature of jupyterlite-xeus is its integration with
emscripten-forge, a conda package distribution tailored for WebAssembly.
This makes it possible to bundle your favorite scientific or data analysis
packages directly into the browser-based environment, delivering a
reproducible computing experience with zero backend dependencies.

Docs:
https://jupyterlite-xeus.readthedocs.io/en/stable/#usage :

> Once installed, you can create an environment.yml file at the root of
your jupyterlite build directory containing the following:

```yaml
name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-lua
  - xeus-nelson
  - numpy
  - matplotlib
  - pillow
  - ipywidgets
  - pip:
      - ipycanvas
```

> Starting with jupyterlite-xeus v4.0.0a11, you can use the %pip and %mamba
magics or the !pip and !mamba commands to install packages dynamically

..

https://github.com/jupyterlite/repo2jupyterlite

https://github.com/jupyterlite/xeus-lite-demo :

> Xeus-Lite demo
> This GitHub template allows you to create deployments of JupyterLite with
a custom set of conda packages

Re: repo2jupyterlite and container2wasm c2w:
https://github.com/container2wasm/container2wasm/issues/550#issue-3709559065

**Comment by ryanking13** [comment]
I would say we are not interested in supportding conda-forge anymore. As [PEP 783](https://peps.python.org/pep-0783/) is accepted now, we are mainly focusing on publishing packages to PyPI, which should be consumable by emscripten-forge or jupyterlite people as well.
